In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['train-balanced-sarcasm.csv']


In [3]:
import pandas as pd
import numpy as np
from sklearn.externals import joblib
import nltk
import gensim
import spacy
from tqdm import tqdm_notebook

from sklearn import metrics
from sklearn.metrics import accuracy_score

import torch as tt
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from torchtext.data import Field, LabelField, BucketIterator, ReversibleField, TabularDataset



SEED = 42
np.random.seed(SEED)

In [4]:
data = pd.read_csv('../input/train-balanced-sarcasm.csv')

In [5]:
data.label.value_counts()

1    505413
0    505413
Name: label, dtype: int64

In [6]:
data.head()

label                        ...                                                             parent_comment
0      0                        ...                          Yeah, I get that argument. At this point, I'd ...
1      0                        ...                          The blazers and Mavericks (The wests 5 and 6 s...
2      0                        ...                                                    They're favored to win.
3      0                        ...                                                 deadass don't kill my buzz
4      0                        ...                          Yep can confirm I saw the tool they use for th...

[5 rows x 10 columns]

In [7]:
import spacy


spacy_en = spacy.load('en')
spacy_en.remove_pipe('tagger')
spacy_en.remove_pipe('ner')

def tokenizer(text): # create a tokenizer function
    return [tok.lemma_ for tok in spacy_en.tokenizer(text)]

In [8]:
classes={
    '0':0,
    '1':1
}

TEXT = Field(include_lengths=True, batch_first=True, 
             tokenize=tokenizer,
             eos_token='<eos>',
             lower=True,
             stop_words=nltk.corpus.stopwords.words('english')
            )
LABEL = LabelField(dtype=tt.int64, use_vocab=True, preprocessing=lambda x: classes[x])

dataset = TabularDataset('../input/train-balanced-sarcasm.csv', format='csv', 
                         fields=[('label', LABEL), ('text', TEXT),(None, None),(None, None), 
                                 (None, None), (None, None), (None, None), (None, None), (None, None), 
                                 (None, None)],
                         skip_header=True)

In [9]:
TEXT.build_vocab(dataset, min_freq=5)
len(TEXT.vocab.itos)

35493

In [10]:
TEXT.vocab.itos[:10]

['<unk>', '<pad>', '<eos>', '.', ',', '-pron-', '?', '!', '"', '...']

In [11]:
LABEL.build_vocab(dataset)

In [12]:
train, test = dataset.split(0.8, stratified=True)
train, valid = train.split(0.9, stratified=True)

In [13]:
np.unique([x.label for x in train.examples], return_counts=True)

(array([0, 1]), array([363897, 363897]))

In [14]:
np.unique([x.label for x in valid.examples], return_counts=True)

(array([0, 1]), array([40433, 40433]))

In [15]:
np.unique([x.label for x in test.examples], return_counts=True)

(array([0, 1]), array([101083, 101083]))

In [16]:
class MyModel(nn.Module):
    
    def __init__(self, vocab_size, embed_size, hidden_size):
        super(MyModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        
        self.rnn = nn.LSTM(input_size=embed_size,
                           hidden_size=hidden_size,
                           bidirectional=True,
                           batch_first=True,
                          )
        
        self.fc = nn.Linear(hidden_size * 2 * 2, 2)
        self.dropout = nn.Dropout(0.5)
        
    def forward(self, batch):
        
        x, x_lengths = batch.text
        
        x = self.embedding(x)

        if x_lengths is not None:
            x_lengths = x_lengths.view(-1).tolist()
            x = nn.utils.rnn.pack_padded_sequence(x, x_lengths, batch_first=True)
            
        _, (hidden, cell) = self.rnn(x)
        
        #hidden = hidden.transpose(0,1)
        cell = cell.transpose(0,1)
        #hidden = hidden.contiguous().view(hidden.size(0),-1)        
        hidden = self.dropout(tt.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1))        
        cell = cell.contiguous().view(cell.size(0),-1)
        x = tt.cat([hidden, cell], dim=1).squeeze(1)
        x = self.fc(x)
        return x

In [17]:
tt.cuda.empty_cache()

batch_size = 32

model = MyModel(len(TEXT.vocab.itos),
                embed_size=100,
                hidden_size=128,
               )



train_iterator, valid_iterator, test_iterator = BucketIterator.splits(
    (train, valid, test),
    batch_sizes=(batch_size, batch_size, batch_size),
    shuffle=True,
    sort_key=lambda x: len(x.text),
    sort_within_batch=True)

optimizer = optim.Adam(model.parameters())
# scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=5, verbose=True, cooldown=5)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=5)
criterion = nn.CrossEntropyLoss()

In [18]:
def _train_epoch(model, iterator, optimizer, criterion, curr_epoch):

    model.train()

    running_loss = 0

    n_batches = len(iterator)
    iterator = tqdm_notebook(iterator, total=n_batches, desc='epoch %d' % (curr_epoch), leave=True)

    for i, batch in enumerate(iterator):
        optimizer.zero_grad()

        pred = model(batch)
        loss = criterion(pred, batch.label)
        loss.backward()
        optimizer.step()

        curr_loss = loss.data.cpu().detach().item()
        
        loss_smoothing = i / (i+1)
        running_loss = loss_smoothing * running_loss + (1 - loss_smoothing) * curr_loss

        iterator.set_postfix(loss='%.5f' % running_loss)

    return running_loss

def _test_epoch(model, iterator, criterion):
    model.eval()
    epoch_loss = 0

    n_batches = len(iterator)
    with tt.no_grad():
        for batch in iterator:
            pred = model(batch)
            loss = criterion(pred, batch.label)
            epoch_loss += loss.data.item()

    return epoch_loss / n_batches

def _test_final(model, iterator, criterion):
    model.eval()
    epoch_loss = 0
    acc_total = 0
    n_batches = len(iterator)
    
    with tt.no_grad():
        for batch in iterator:
            y_pred = tt.nn.functional.softmax(model(batch), dim=1).detach().numpy().argmax(axis=1)
            acc_score = metrics.accuracy_score(y_pred, batch.label)
            acc_total += acc_score

    return acc_total / n_batches


def nn_train(model, train_iterator, valid_iterator, criterion, optimizer, n_epochs=100,
          scheduler=None, early_stopping=0):

    prev_loss = 100500
    es_epochs = 0
    best_epoch = None
    history = pd.DataFrame()

    for epoch in range(n_epochs):
        train_loss = _train_epoch(model, train_iterator, optimizer, criterion, epoch)
        valid_loss = _test_epoch(model, valid_iterator, criterion)

        valid_loss = valid_loss
        print('validation loss %.5f' % valid_loss)

        record = {'epoch': epoch, 'train_loss': train_loss, 'valid_loss': valid_loss}
        history = history.append(record, ignore_index=True)

        if early_stopping > 0:
            if valid_loss > prev_loss:
                es_epochs += 1
            else:
                es_epochs = 0

            if es_epochs >= early_stopping:
                best_epoch = history[history.valid_loss == history.valid_loss.min()].iloc[0]
                print('Early stopping! best epoch: %d val %.5f' % (best_epoch['epoch'], best_epoch['valid_loss']))
                break

            prev_loss = min(prev_loss, valid_loss)

In [19]:
nn_train(model, train_iterator, valid_iterator, criterion, optimizer, scheduler=scheduler, 
        n_epochs=10, early_stopping=2)


validation loss 0.55824



validation loss 0.55539



validation loss 0.56382



validation loss 0.58383
Early stopping! best epoch: 1 val 0.55539


In [22]:
count_test_accuracy(model, test_iterator)

0.7095082772166105

Baseline 0.7 accuracy побит! Ура-ура!

In [21]:
def count_test_accuracy(model, test_iterator):
    
    model.eval()
    
    epoch_acc, n_batches = 0, len(test_iterator)
    
    with tt.no_grad():
        for batch in test_iterator:
            
            pred = model(batch)
            
            
            pred = tt.softmax(pred, dim=-1)
            pred = pred.detach().numpy()
            
            accuracy = accuracy_score(batch.label, pred.argmax(axis=1))
            epoch_acc += accuracy.item()
            
        
    return epoch_acc / n_batches